#
# Author: github.com/luncliff (luncliff@gmail.com)
#

jobs:
  - job: vuepress
    pool:
      vmImage: "macos-latest"
    steps:
      - script: brew install doxygen
      - script: python3 -m pip install --user -r requirements.txt
      - script: doxygen ./docs/Doxyfile
      # doxybook - vuepress
      - script: python3 -m doxybook -i ./docs/xml -o ./docs -t vuepress
      - script: npm install -D vuepress
      - script: npm run build
      # https://v1.vuepress.vuejs.org/guide/deploy.html#github-pages
      # - script: bash ./scripts/release-docs.sh
