#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters
#

jobs:
  - job: vs2019_cmake_ninja_clang8
    pool:
      vmImage: windows-2019
    variables:
      visualstudio: 2019
      configuration: Debug
      is_dynamic: True
    steps:
      - template: steps-win-llvm.yml # uses relative path
        parameters:
          llvm_version: "8.0.1"

  - job: vs2019_cmake_ninja_clang_latest
    pool:
      vmImage: windows-2019
    steps:
      - task: ChocolateyCommand@0
        inputs:
          command: "install"
          installPackageId: "ninja"
          installInstallArgs: "--no-progress --yes"

      - task: ChocolateyCommand@0
        inputs:
          command: "install"
          installPackageId: "llvm"
          installInstallArgs: "--no-progress --yes"

      - task: BatchScript@1
        inputs:
          filename: "./scripts/build-vs2019-cmake-clang.bat"
        env:
          SHARED: True
          BUILD_TYPE: Debug
