#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters
#

jobs:
  - job: documentation
    pool:
      vmImage: "macos-latest"
    steps:
      - script: brew install tree
      - script: brew install doxygen
      - script: python3 -m pip install --user -r ./docs/requirements.txt
      - script: doxygen ./docs/Doxyfile
      - script: sphinx-build ./docs/ ./docs/sphinx
      - script: tree -L 2 ./docs/sphinx
      # - script: Invoke-Item ./docs/sphinx/index.html
