#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters
#

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            sudo bash ./scripts/setup-compilers-ubuntu.sh;
            sudo apt install -y -qq --fix-missing rsync wget unzip;
            sudo bash ./scripts/install-libcxx.sh;
      - task: CMake@1
        inputs:
          cmakeArgs: . -DBUILD_SHARED_LIBS=true -DCMAKE_CXX_COMPILER=clang
          workingDirectory: "."
      - task: CMake@1
        inputs:
          cmakeArgs: --build .
          workingDirectory: "."
      # - task: Bash@3
      #   inputs:
      #     targetType: "inline"
      #     script: ctest --output-on-failure
      #   timeoutInMinutes: 1
