#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters
#

jobs:
  - job: VS${{ parameters.visualstudio }}Clang8
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - task: ChocolateyCommand@0
        inputs:
          command: "install"
          installPackageId: "ninja"
          installInstallArgs: "--no-progress --yes"
      - task: ChocolateyCommand@0
        inputs:
          command: "install"
          # https://chocolatey.org/packages/llvm/8.0.1
          installPackageId: "llvm"
          installInstallArgs: "--no-progress --yes --force --allow-downgrade --version=8.0.1"
      - task: BatchScript@1
        inputs:
          filename: "./scripts/build-vs2017-cmake-clang.bat"
        env:
          SHARED: False
          BUILD_TYPE: Debug
        

  - job: VS${{ parameters.visualstudio }}MSVC
    pool:
      vmImage: "vs2017-win2016"
    variables:
      configuration: debug
      platform: x64
    steps:
      - task: PowerShell@2
        inputs:
          targetType: "inline"
          script: systeminfo;
      - task: CMake@1
        inputs:
          cmakeArgs: . -A x64 -DBUILD_SHARED_LIBS=true
          workingDirectory: "."  
      - task: MSBuild@1
        inputs:
          solution: ${{ parameters.solution }}
          msbuildArchitecture: $(platform)
          platform: $(platform)
          configuration: $(configuration)
          msbuildArguments: "/p:platformtoolset=v141"
      # - task: VSTest@2
      #   inputs:
      #     testAssemblyVer2: |
      #       **\*vstest*.dll
      #     codeCoverageEnabled: true
