#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#passing-parameters
#

jobs:
  - job: vs${{ parameters.visualstudio }}_cmake_vs_msvc
    pool:
      #
      # See Also
      #   https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md
      #
      vmImage: ${{ parameters.vmimage }}
    variables:
      platform: x64
    steps:
      - task: PowerShell@2
        inputs:
          targetType: "inline"
          script: systeminfo;
      - task: CMake@1
        inputs:
          cmakeArgs: . -A $(platform) -DBUILD_SHARED_LIBS=${{ parameters.make_shared }}
          workingDirectory: "."
      - task: MSBuild@1
        inputs:
          solution: '**/*.sln'
          msbuildArchitecture: $(platform)
          platform: $(platform)
          configuration: ${{ parameters.configuration }}
          msbuildArguments: "/p:platformtoolset=${{ parameters.toolset }}"

      # - task: VSTest@2
      #   inputs:
      #     testAssemblyVer2: |
      #       **\*vstest*.dll
      #     codeCoverageEnabled: true
      #   continueOnError: true
