#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent
#   https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md
#

jobs:
- job: vs2017_cmake_vs_msvc
  pool:
    vmImage: vs2017-win2016
  variables:
    platform: x64
    configuration: Debug
    is_dynamic: True
  steps:
    - template: azure/steps-win-vs.yml
      parameters:
        toolset: v141

- job: vs2019_cmake_vs_msvc
  pool:
    vmImage: windows-2019
  variables:
    platform: x64
    configuration: Debug
    is_dynamic: True
  steps:
    - template: azure/steps-win-vs.yml
      parameters:
        toolset: v142

- job: vs2017_cmake_ninja_clang_8
  pool:
    vmImage: vs2017-win2016
  variables:
    visualstudio: '2017'
    configuration: Debug
    is_dynamic: True
  steps:
    - template: azure/steps-win-llvm.yml
      parameters:
        llvm_version: '8.0.1'

- job: vs2017_cmake_ninja_clang_9
  pool:
    vmImage: vs2017-win2016
  variables:
    visualstudio: '2017'
    configuration: Debug
    is_dynamic: True
  steps:
    - template: azure/steps-win-llvm.yml
      parameters:
        llvm_version: '9.0.0'

- job: vs2019_cmake_ninja_clang_8
  pool:
    vm_image: windows-2019
  variables:
    visualstudio: '2019'
    configuration: Debug
    is_dynamic: True
  steps:
    - template: azure/steps-win-llvm.yml
      parameters:
        llvm_version: '8.0.1'

- job: vs2019_cmake_ninja_clang_9
  pool:
    vm_image: windows-2019
  variables:
    visualstudio: '2019'
    configuration: Debug
    is_dynamic: True
  steps:
    - template: azure/steps-win-llvm.yml
      parameters:
        llvm_version: '9.0.0'

# - template: azure/vm-ubuntu-16.04.yml
#   parameters:
#     name: Ubuntu1604

# - template: azure/vm-macos-latest.yml
#   parameters:
#     name: MacOS
