#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent
#

jobs:
- template: azure/vm-vs2017-win2016.yml
  parameters:
    visualstudio: '2017'
    solution: '**/*.sln'

- template: azure/vm-windows-2019.yml
  parameters:
    visualstudio: '2019'
    solution: '**/*.sln'

- template: azure/vm-ubuntu-16.04.yml
  parameters:
    name: Ubuntu1604

- template: azure/vm-macos-latest.yml
  parameters:
    name: MacOS
