#
# Author: github.com/luncliff (luncliff@gmail.com)
#
# References
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent
#

jobs:
- template: azure/vm-win-vs.yml
  parameters:
    visualstudio: '2017'
    toolset: v141
    vm_image: 'vs2017-win2016'
    make_shared: True
    configuration: 'Debug'

- template: azure/vm-win-vs.yml
  parameters:
    visualstudio: '2019'
    toolset: v142
    vm_image: 'windows-2019'
    make_shared: True
    configuration: 'Debug'

- template: azure/vm-win-llvm.yml
  parameters:
    visualstudio: '2017'
    vm_image: 'vs2017-win2016'
    make_shared: True
    configuration: 'Debug'

- template: azure/vm-win-llvm.yml
  parameters:
    visualstudio: '2019'
    vm_image: 'windows-2019'
    make_shared: True
    configuration: 'Debug'

- template: azure/vm-ubuntu-16.04.yml
  parameters:
    name: Ubuntu1604

- template: azure/vm-macos-latest.yml
  parameters:
    name: MacOS
