#
# Author: github.com/luncliff (luncliff@gmail.com)
# References:
#   https://www.mkdocs.org/
#   https://github.com/squidfunk/mkdocs-material
#   https://material.io/resources/icons/?icon=call_split&style=twotone
#   https://fonts.google.com/
#
site_name: Simple Socket Functions
site_url: https://luncliff.github.io/ssf

repo_name: luncliff/ssf
repo_url: https://github.com/luncliff/ssf

nav:
  - Modules: index_groups.md
  - Classes: index_classes.md
  - Files: index_files.md

markdown_extensions:
  - admonition
  - codehilite
  # - toc:
  #     permalink: true
  - pymdownx.highlight:
      # anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

# plugins:
#   - git-revision-date

theme:
  name: "material"
  palette:
    scheme: slate
    primary: deep purple
  icon:
    logo: material/library # check mkdocs-material 'materials/.icon/*.svg'
  features:
    - content.code.copy
    - content.tabs.link

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/luncliff"
