name: "CMake"

on:
  push:
    branches-ignore:    
      - 'docs'
  pull_request:
    branches-ignore:    
      - 'docs'

jobs:
  build_macos:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: "Install Tools"
      run: brew install ninja
    - name: run-cmake
      uses: lukka/run-cmake@v10.3
      with:
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        configurePreset: x64-osx-debug
        buildPreset: x64-osx-debug
        testPreset: x64-osx-debug

  build_windows:
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
    runs-on: windows-2022
    strategy:
      matrix:
        triplet: [ x64-windows ]
    steps:
    - uses: actions/checkout@v3
    - name: run-cmake
      uses: lukka/run-cmake@v10.3
      with:
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        # configurePreset: ${{ matrix.triplet }}
        # buildPreset: ${{ matrix.triplet }}-debug
        # testPreset: ${{ matrix.triplet }}-debug
        workflowPreset: ${{ matrix.triplet }}-debug
