name: "Tag: Sample"

on:
  push:
    tags:
      - '*'

jobs:
  build_x64:
    runs-on: windows-2022
    strategy:
      matrix:
        triplet: [ x64-windows ]
    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
