name: "Tag: Sample"

on:
  push:
    tags:
      - '**'

jobs:
  build_x64:
    runs-on: windows-2022
    env:
      VCPKG_ROOT: "C:\\vcpkg"
    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
        submodules: false
    - uses: lukka/run-cmake@v10.3
      with:
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        configurePreset: "x64-windows"
        configurePresetAdditionalArgs: "['-DCMAKE_INSTALL_DEBUG_LIBRARIES=1']"
        buildPreset: "x64-windows-debug"
        buildPresetAdditionalArgs: "['--target install']"
    - uses: actions/upload-artifact@v3
      with:
        name: x64-windows-debug
        path: install
